### ISSUE TITLE
Добавишь меня в разработчики?

### ISSUE THREAD

**Issue by binarymaster** [majackov/3wifi-telegram-bot#1]
Привет! Вот спустя пару лет решил освежить код телегобота для 3WiFi, создал свой форк с улучшениями: https://github.com/binarymaster/3wifi-telegram-bot

Добавишь меня в разработчики, чтобы я мог пушить код в твой репозиторий напрямую? :slightly_smiling_face: 

**Project > Settings > Collaborators**, или ссылкой: https://github.com/majackov/3wifi-telegram-bot/settings/collaboration

**Comment by alcomic** [comment]
Привет. Отправил инвайт, проверяй
ПС можно еще посмотреть и обновить зависимости, если скрипт будет работать 🙃

**Comment by binarymaster** [comment]
Получилось, спасибо! :grin: 

Естественно перед тем как коммитить, у себя всё проверил, всё работает.
